#!/bin/bash
#SBATCH --job-name=R-serial      # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=4G         # memory per cpu-core (4G per cpu-core is default)
#SBATCH --time=00:01:00          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=all          # send email on start, end and fault
#SBATCH --mail-user=<YourNetID>@princeton.edu

#do we need to refresh the modules ? 
#spack module tcl refresh -y

module purge
module load proj
module load r/4.4.0-gcc-12.2.0-fpmyijt 

/home/u/modeling/opt/spack/linux-rocky8-haswell/gcc-12.2.0/r-4.4.0-fpmyijtotlxdrldrv3fz6wssloku5qsi/bin/Rscript test.R
#Rscript myscript.R